languageCode = "en-us"
title = "Paligo WCAG review"
baseURL = "https://duff92.github.io/cupper"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Paligo** WCAG 2.2 AA review, built with **Cupper**."
  codePenUser = "duff92"
